[tool.poetry]
name = "akneurolab"
version = "0.1.0"
description = ""
authors = ["Adesh <adeshkadambi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.27.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
